// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4IYVZgr1WK8VaAeMnSqetNVHljwa_esQ',
    appId: '1:825374792631:web:76a1d312922987ab5be632',
    messagingSenderId: '825374792631',
    projectId: 'jobinterview-f9d01',
    authDomain: 'jobinterview-f9d01.firebaseapp.com',
    storageBucket: 'jobinterview-f9d01.firebasestorage.app',
    measurementId: 'G-JS9M5RYR05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMomfiPZbN1nDgw-oT9uG46RVNSq90d5k',
    appId: '1:825374792631:android:6fe733256dd43fde5be632',
    messagingSenderId: '825374792631',
    projectId: 'jobinterview-f9d01',
    storageBucket: 'jobinterview-f9d01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqIT1tUgXlkqx77rQZQo7cN_SOzSohVmw',
    appId: '1:825374792631:ios:1ff8116d9de65dcf5be632',
    messagingSenderId: '825374792631',
    projectId: 'jobinterview-f9d01',
    storageBucket: 'jobinterview-f9d01.firebasestorage.app',
    iosBundleId: 'com.example.job',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqIT1tUgXlkqx77rQZQo7cN_SOzSohVmw',
    appId: '1:825374792631:ios:1ff8116d9de65dcf5be632',
    messagingSenderId: '825374792631',
    projectId: 'jobinterview-f9d01',
    storageBucket: 'jobinterview-f9d01.firebasestorage.app',
    iosBundleId: 'com.example.job',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4IYVZgr1WK8VaAeMnSqetNVHljwa_esQ',
    appId: '1:825374792631:web:8cf7d2317f4f5ac25be632',
    messagingSenderId: '825374792631',
    projectId: 'jobinterview-f9d01',
    authDomain: 'jobinterview-f9d01.firebaseapp.com',
    storageBucket: 'jobinterview-f9d01.firebasestorage.app',
    measurementId: 'G-YZW400NHN4',
  );
}
